### ISSUE TITLE
Deno client

### ISSUE THREAD

**Issue by tj** [apex/rpc#7]
Not sure if it would differ much from the TypeScript/JS Node one, maybe not if it has `fetch()`

**Comment by tj** [comment]
almost works, will try to check this out tomorrow

```
error: TS2580 [ERROR]: Cannot find name 'require'. Do you need to install type definitions for node? Try `npm i @types/node`.
  fetch = require('node-fetch')
          ~~~~~~~
    at file:///Users/tj/dev/src/github.com/apex/logs/js/src/index.ts:696:11

TS2721 [ERROR]: Cannot invoke an object which is possibly 'null'.
 const res = await fetch(url + '/' + method, {
                   ~~~~~
    at file:///Users/tj/dev/src/github.com/apex/logs/js/src/index.ts:705:20

TS2339 [ERROR]: Property 'type' does not exist on type 'Error'.
 	 err.type = type
 	     ~~~~
    at file:///Users/tj/dev/src/github.com/apex/logs/js/src/index.ts:721:8

TS2322 [ERROR]: Type 'string | undefined' is not assignable to type 'string'.
  Type 'undefined' is not assignable to type 'string'.
    this.authToken = params.authToken
    ~~~~~~~~~~~~~~
    at file:///Users/tj/dev/src/github.com/apex/logs/js/src/index.ts:749:5
```

**Comment by tj** [comment]
680dc93
